name: Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  call-deploy:
    uses: Grupo-Potencial-IA-e-Inovacao/workflows/.github/workflows/deploy-dev.yml@main
    secrets:
      EASYPANEL_DEPLOY_WEBHOOK_DEV: ${{ secrets.EASYPANEL_DEPLOY_WEBHOOK_DEV }}
