name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read

jobs:
  call-release:
    uses: Grupo-Potencial-IA-e-Inovacao/workflows/.github/workflows/release.yml@main
